### ISSUE TITLE
Heatpump not discovered

### ISSUE THREAD

**Issue by nisarerbest** [klejejs/python-thermia-online-api#1]
Hi @klejejs.

Thanks for this awesome Home Assistant Thermia connectivity. My heatpump (Atlas 12) uses the API: https://online-genesis.thermia.se/api/configuration

So when I try to connect to online.thermia.se, No heatpump is discovered. Is it a completely different API, or just different link?

Thanks!

**Comment by klejejs** [comment]
Hello. Thanks for making the issue.

I didn't realize there could be different API URLs, that's why this was never implemented.
I just created an API release as a fix, from what I could tell using a demo account, the APIs are pretty similar, so it should work. Nevertheless, if you notice any errors, please report them, I'd be happy to look into it.

P.S. The Home Assistant integration will be updated a bit later as I have to change the config flow for it.

**Comment by klejejs** [comment]
I also just updated the Home Assistant integration. During installation, you will have to choose the `genesis` API type.

Please let me know if it works 😉

**Comment by nisarerbest** [comment]
Thank you so much for adding. I managed to see my heat pump! :-) 3 entities are visible:
- water heater
- active alarm
- hot water switch
From the readme, it seems like a lot more entities should be exposed

**Comment by klejejs** [comment]
This is the API repository which exposes a lot different entities. Those are all used together to expose 3 entities in Home Assistant - the ones you mentioned above.

More info regarding that is in [Integration Repository](https://github.com/klejejs/ha-thermia-heat-pump-integration/).

If you think there are other entities you would find useful in Home Assistant, I'd be happy to look into that, but I'd appreciate if in that case you created a feature request in integration repository.

**Comment by klejejs** [comment]
Closing as the issue has been fixed.
