### ISSUE TITLE
Authentification error

### ISSUE THREAD

**Issue by Vovanoso** [klejejs/python-thermia-online-api#35]
Launching example.py I have got issue
Traceback (most recent call last):
  File "C:\Users\ganet\PycharmProjects\pythonProject\Thermia\Sql\example.py", line 13, in <module>
    thermia = Thermia(USERNAME, PASSWORD)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ganet\Pycharm\Lib\site-packages\ThermiaOnlineAPI\__init__.py", line 13, in __init__
    self.api_interface = ThermiaAPI(username, password)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ganet\Pycharm\Lib\site-packages\ThermiaOnlineAPI\api\ThermiaAPI.py", line 73, in __init__
    self.authenticated = self.__authenticate()
                         ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ganet\Pycharm\Lib\site-packages\ThermiaOnlineAPI\api\ThermiaAPI.py", line 680, in __authenticate
    "code": request_confirmed.url.split("code=")[1],
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

Process finished with exit code 1

**Comment by fclauson** [comment]
It seems that the portal has a new agreement you have to agree to So sign in on line can click ok The this will work again Francis Clauson - 087 11 500 33On 27 Jun 2024, at 11:50, Vovanoso ***@***.***> wrote:﻿
Launching example.py I have got issue
Traceback (most recent call last):
File "C:\Users\ganet\PycharmProjects\pythonProject\Thermia\Sql\example.py", line 13, in 
thermia = Thermia(USERNAME, PASSWORD)
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\ganet\Pycharm\Lib\site-packages\ThermiaOnlineAPI_init_.py", line 13, in init
self.api_interface = ThermiaAPI(username, password)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\ganet\Pycharm\Lib\site-packages\ThermiaOnlineAPI\api\ThermiaAPI.py", line 73, in init
self.authenticated = self.__authenticate()
^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\ganet\Pycharm\Lib\site-packages\ThermiaOnlineAPI\api\ThermiaAPI.py", line 680, in __authenticate
"code": request_confirmed.url.split("code=")[1],
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
Process finished with exit code 1

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**Comment by klejejs** [comment]
@Vovanoso can you please confirm if that is the case @fclauson mentioned? Some other people have also commented on this issue and it has not yet been clear to me what exactly is wrong.

**Comment by wouterse** [comment]
I had the same issue, and the fix that @fclauson mentioned worked for me.

**Comment by Gjorret** [comment]
I can confirm the same, got the same error and couldnt connect. After logging into their web portal and accepting the agreement then it works again.

> Exception has occurred: IndexError
> list index out of range
>   File "C:\Scripts\Thermia\ThermiaOnlineAPI\api\ThermiaAPI.py", line 655, in __authenticate
>     "code": request_confirmed.url.split("code=")[1],
>             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
>   File "C:\Scripts\Thermia\ThermiaOnlineAPI\api\ThermiaAPI.py", line 78, in __init__
>     self.authenticated = self.__authenticate()
>                          ^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Scripts\Thermia\ThermiaOnlineAPI\__init__.py", line 14, in __init__
>     self.api_interface = ThermiaAPI(username, password, api_type)
>                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Scripts\Thermia\collectdata.py", line 15, in <module>
>     thermia = Thermia(USERNAME, PASSWORD, "classic")
>               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> IndexError: list index out of range

![image](https://github.com/klejejs/python-thermia-online-api/assets/6999484/336c70b7-b65c-4741-9f8c-2b8dac58848f)

**Comment by Swifster** [comment]
Hi!

I went to online and agreed to the new terms and all worked after this.
